#
#  this box is for doing experiment with k3
#
$system_setup = <<END_OF_SETUP

apt-get update
apt-get install -y git nfs-common peco jq net-tools open-iscsi

END_OF_SETUP


Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2004"
    config.vm.box_check_update = false

    config.vm.network :public_network, dev: "enp3s0", use_dhcp_assigned_default_route: true

    config.vm.provider "libvirt" do |v|
	    v.memory = 4096
	    v.cpus = 1
    end

    config.vm.synced_folder "setup", "/home/vagrant/setup",
        type: "rsync",
        rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "--delete", "-z"]

    config.vm.define :s1 do |s|
    config.vm.provision "shell", inline: $system_setup
        s.vm.synced_folder "bin", "/usr/local/bin", type: "rsync"
        s.vm.provision "shell", inline: "sudo hostnamectl set-hostname k3s1"
    end

    config.vm.define :s2 do |s|
        s.vm.provision "shell", inline: "sudo hostnamectl set-hostname k3s2"
    end

    config.vm.define :s3 do |s|
        s.vm.provision "shell", inline: "sudo hostnamectl set-hostname k3s3"
    end

end
