apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 4h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.2.26
      pullPolicy: IfNotPresent

    guiService:
      type: LoadBalancer

    captivePortalService:
      enabled: false

    controllerService:
      type: LoadBalancer

    speedtestService:
      type: LoadBalancer

    timezone: Asia/Singapore

    # -- If you provide your own custom certificate in <unifi-data>/cert
    # you can define the following parameters to configure the controller
    customCert:
      enabled: false
      # certSecret: unifi-tls

    mongodb:
      enabled: true
      dbUri: mongodb://mongodb.mongo.svc.cluster.local/unifi
      statDbUri: mongodb://mongodb.mongo.svc.cluster.local/unifi_stat
      databaseName: unifi

    persistence:
      enabled: true
      storageClass: managed-nfs-storage
      existingClaim:
      accessMode: ReadWriteOnce
      size: 3Gi
      skipuninstall: false

    jvmInitHeapSize:
    jvmMaxHeapSize: 1024M

