apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: prometheus
  chart:
    spec:
      chart:
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "17.0.2"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
